# Generated by Django 5.2.17 on 2026-08-31 11:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_hosts', models.IntegerField(default=0)),
                ('total_gpus', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('active_sessions', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('new_users', models.IntegerField(default=0)),
                ('new_hosts', models.IntegerField(default=0)),
                ('new_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='platform_an_date_7b03e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('sessions', 'Session Overview'), ('earnings', 'Earnings & Revenue'), ('gpus', 'GPU Inventory'), ('reviews', 'Ratings & Reviews'), ('wallet', 'Wallet & Balance'), ('activity', 'Recent Activity'), ('system_metrics', 'System Performance'), ('platform_stats', 'Platform Overview')], max_length=50)),
                ('position', models.IntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['user', 'is_active', 'position'], name='dashboard_w_user_id_b47a31_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_activi_user_id_543519_idx'), models.Index(fields=['action', '-created_at'], name='user_activi_action_5db802_idx'), models.Index(fields=['-created_at'], name='user_activi_created_66afa1_idx')],
            },
        ),
    ]
