# Generated by Django 5.2.17 on 2026-08-31 10:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gpu_sessions', '0002_hostearning_hostpenaltylog'),
        ('gpus', '0002_alter_gpu_price_per_hour'),
        ('users', '0002_hostprofile_auto_accept_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Overall rating (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(default=5, help_text='How responsive was the host? (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reliability_rating', models.IntegerField(default=5, help_text='Did the host stay online and maintain stable service? (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('gpu_performance_rating', models.IntegerField(default=5, help_text='Was the GPU fast and performing as expected? (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='', help_text='Detailed feedback from the renter')),
                ('is_verified', models.BooleanField(default=True, help_text='Indicates review is from a verified completed rental session')),
                ('host_response', models.TextField(blank=True, help_text='Optional response from the host', null=True)),
                ('host_responded_at', models.DateTimeField(blank=True, help_text='Timestamp when host responded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gpu', models.ForeignKey(help_text='GPU used during the session', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gpus.gpu')),
                ('host', models.ForeignKey(help_text='Host profile being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='users.hostprofile')),
                ('renter', models.ForeignKey(help_text='Renter who authored this review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(help_text='The completed rental session associated with this review', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='gpu_sessions.session')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['host', '-created_at'], name='reviews_host_id_a237f0_idx'), models.Index(fields=['gpu', '-created_at'], name='reviews_gpu_id_bfcacf_idx'), models.Index(fields=['renter', '-created_at'], name='reviews_renter__a3258f_idx'), models.Index(fields=['rating'], name='reviews_rating_17e8a4_idx'), models.Index(fields=['is_verified'], name='reviews_is_veri_aa479e_idx')],
            },
        ),
    ]
