# Generated by Django 5.2.17 on 2026-08-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostprofile',
            name='auto_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='max_rental_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='pending_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='total_rental_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
