# Generated by Django 5.2.17 on 2026-08-30 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('session_started', 'Session Started'), ('session_ending', 'Session Ending Soon'), ('session_completed', 'Session Completed'), ('session_terminated', 'Session Terminated'), ('refund_processed', 'Refund Processed'), ('payment_received', 'Payment Received'), ('host_offline', 'Host Offline'), ('new_session_request', 'New Session Request'), ('wallet_credited', 'Wallet Credited'), ('wallet_debited', 'Wallet Debited'), ('welcome', 'Welcome'), ('system_alert', 'System Alert'), ('penalty_applied', 'Penalty Applied')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
