# Generated by Django 5.2.17 on 2026-08-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('session_started', 'Session Started'), ('session_ending', 'Session Ending Soon'), ('session_completed', 'Session Completed'), ('session_terminated', 'Session Terminated'), ('refund_processed', 'Refund Processed'), ('payment_received', 'Payment Received'), ('host_offline', 'Host Offline'), ('new_session_request', 'New Session Request'), ('wallet_credited', 'Wallet Credited'), ('wallet_debited', 'Wallet Debited'), ('welcome', 'Welcome'), ('system_alert', 'System Alert'), ('penalty_applied', 'Penalty Applied'), ('review_received', 'Review Received'), ('review_response', 'Host Responded to Review')], max_length=50),
        ),
    ]
