# Generated by Django 5.2.17 on 2026-08-28 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gpus', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayPort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('port', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('free', 'Free'), ('leased', 'Leased'), ('reserved', 'Reserved')], default='free', max_length=20)),
                ('leased_to_session_id', models.UUIDField(blank=True, null=True)),
                ('leased_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'relay_ports',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('starting', 'Starting'), ('container_running', 'Container Running'), ('tunnel_connecting', 'Tunnel Connecting'), ('active', 'Active'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('relay_server_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('relay_server_port', models.IntegerField(blank=True, null=True)),
                ('relay_auth_key', models.TextField(blank=True, null=True)),
                ('ssh_connection_string', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('active_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(default=0.0)),
                ('actual_cost', models.FloatField(blank=True, null=True)),
                ('refund_amount', models.FloatField(default=0.0)),
                ('compensation_amount', models.FloatField(default=0.0)),
                ('platform_fee', models.FloatField(default=0.0)),
                ('work_protection_enabled', models.BooleanField(default=False)),
                ('work_protection_fee', models.FloatField(default=0.0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('work_lost', models.BooleanField(default=False)),
                ('termination_reason', models.CharField(blank=True, choices=[('host_offline', 'Host Offline'), ('renter_stopped', 'Renter Stopped'), ('completed', 'Completed'), ('failed', 'Failed'), ('host_rejected', 'Host Rejected'), ('idle_timeout', 'Idle Timeout'), ('admin_cancelled', 'Admin Cancelled')], max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gpus.gpu')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.hostprofile')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gpu_temperature_c', models.FloatField(blank=True, null=True)),
                ('gpu_utilization_pct', models.FloatField(blank=True, null=True)),
                ('memory_used_mib', models.FloatField(blank=True, null=True)),
                ('memory_total_mib', models.FloatField(blank=True, null=True)),
                ('power_usage_w', models.FloatField(blank=True, null=True)),
                ('fan_speed_pct', models.FloatField(blank=True, null=True)),
                ('cpu_usage_pct', models.FloatField(blank=True, null=True)),
                ('ram_usage_mb', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='gpu_sessions.session')),
            ],
            options={
                'db_table': 'session_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='sessions_status_2c94db_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['host', 'status'], name='sessions_host_id_f4513e_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['renter', 'status'], name='sessions_renter__ec1fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['gpu', '-created_at'], name='sessions_gpu_id_ed373a_idx'),
        ),
    ]
