# Generated by Django 5.2.17 on 2026-08-29 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_sessions', '0001_initial'),
        ('users', '0002_hostprofile_auto_accept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='users.hostprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_earnings', to='gpu_sessions.session')),
            ],
            options={
                'db_table': 'host_earnings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['host', '-created_at'], name='host_earnin_host_id_55fa20_idx'), models.Index(fields=['status'], name='host_earnin_status_5471bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='HostPenaltyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('penalty_points', models.IntegerField()),
                ('reason', models.TextField()),
                ('appeal_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20)),
                ('appeal_reason', models.TextField(blank=True, null=True)),
                ('appealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='users.hostprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='gpu_sessions.session')),
            ],
            options={
                'db_table': 'host_penalties',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['host', '-created_at'], name='host_penalt_host_id_fbac43_idx')],
            },
        ),
    ]
