# Generated by Django 5.2.17 on 2026-08-27 15:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gpu_name', models.CharField(help_text='e.g., NVIDIA RTX 4090', max_length=255)),
                ('vram_total', models.CharField(help_text='e.g., 24576 MiB', max_length=50)),
                ('vram_gb', models.IntegerField(help_text='VRAM in GB, e.g., 24')),
                ('cuda_cores', models.IntegerField(blank=True, null=True)),
                ('memory_bandwidth', models.CharField(blank=True, max_length=50, null=True)),
                ('compute_capability', models.CharField(blank=True, max_length=10, null=True)),
                ('driver_version', models.CharField(blank=True, max_length=50, null=True)),
                ('cuda_version', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, help_text='Price in NPR per hour', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_available', models.BooleanField(default=True)),
                ('current_session_id', models.UUIDField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('total_rental_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpus', to='users.hostprofile')),
            ],
            options={
                'db_table': 'gpus',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['host', '-created_at'], name='gpus_host_id_b96aba_idx'), models.Index(fields=['is_available'], name='gpus_is_avai_3473b0_idx'), models.Index(fields=['vram_gb'], name='gpus_vram_gb_50081f_idx'), models.Index(fields=['price_per_hour'], name='gpus_price_p_878006_idx'), models.Index(fields=['location'], name='gpus_locatio_e77465_idx')],
            },
        ),
    ]
