# Generated by Django 5.2.17 on 2026-08-31 10:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, help_text='Price in NPR per hour', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
